#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

touch /etc/fstab

root=`cat /proc/cmdline | grep -o '\broot=[^ ]*' | cut -d = -f 2`
if test -z "$root"
then
    exit 1
fi

if [ "$root" = "9p" ]
then
    mount -t 9p -o msize=131072,trans=xen share_dir /mnt
else
    mount $root /mnt
fi

mkdir /mnt/dev &>/dev/null
mkdir /mnt/sys &>/dev/null
mkdir /mnt/proc &>/dev/null
mount -o bind /dev /mnt/dev
mount -o bind /sys /mnt/sys
mount -o bind /proc /mnt/proc

ip=`cat /proc/cmdline | grep -o '\bip=[^ ]*' | cut -d = -f 2`
gw=`cat /proc/cmdline | grep -o '\bgw=[^ ]*' | cut -d = -f 2`
route=`cat /proc/cmdline | grep -o '\broute=[^ ]*' | cut -d = -f 2`
if test "$ip"
then
	# ipv4
	if [ "$ip" != "${ip#*[0-9].[0-9]}" ]
	then
		ifconfig eth0 $ip up
		if [ "$route" ] && [ "$gw" ]
		then
			route add -net $route gw $gw eth0
		fi
		mkdir -p /mnt/etc
		echo "nameserver 8.8.8.8" > /mnt/etc/resolv.conf
	# ipv6
	elif [ "$ip" != "${ip#*:[0-9a-fA-F]}" ]
	then
		ifconfig eth0 add $ip up
		if [ "$route" ] && [ "$gw" ]
		then
			route -A inet6 add $route gw $gw eth0
		fi
		mkdir -p /mnt/etc
		echo "nameserver 2001:4860:4860::8888" > /mnt/etc/resolv.conf
	fi
fi
