#!/bin/bash

base="`pwd`/initrd"
outpath="$base"/out
tmpdir=`mktemp -d`
tmpfile=`mktemp`
initrd=$outpath/initrd
init="$base"/init-initrd
rm -rf $tmpdir

if test -z "$busybox"
then
    busybox=$(which busybox)
fi

mkdir -p $outpath
mkdir -p $tmpdir/bin
mkdir -p $tmpdir/sbin
mkdir -p $tmpdir/etc
mkdir -p $tmpdir/dev
mkdir -p $tmpdir/proc
mkdir -p $tmpdir/sys
mkdir -p $tmpdir/lib
mkdir -p $tmpdir/var
mkdir -p $tmpdir/mnt
cp "$busybox" $tmpdir/bin/busybox
$tmpdir/bin/busybox --install $tmpdir/bin

mkdir -p $tmpdir/etc/init.d
cp $init $tmpdir/etc/init.d/rcS
chmod +x $tmpdir/etc/init.d/rcS

cp "$base"/inittab $tmpdir/etc/inittab
cp "$base"/passwd $tmpdir/etc/passwd

cp "$base"/autologin $tmpdir/bin
chmod +x $tmpdir/bin/autologin
cp "$base"/enter $tmpdir/bin
chmod +x $tmpdir/bin/enter

cd $tmpdir
find . | cpio --create --format='newc' > $tmpfile
gzip < $tmpfile > $initrd
sync

rm -rf $tmpdir
rm -rf $tmpfile
