#!/bin/bash

base="`pwd`/initrd"
builddir="$base"/build
outpath="$base"/out
tmpdir=`mktemp -d`
tmpfile=`mktemp`
initrd=$outpath/initrd
init="$base"/init-initrd
rm -rf $tmpdir


if test -z "$busybox"
then
    busybox_version=1.32.0
    busybox_name=busybox-$busybox_version
    busybox_tarball="$busybox_name".tar.bz2
    busybox_url="https://busybox.net/downloads/""$busybox_tarball"
    busybox_src_config="$base"/config."$ARCH"
    busybox_image="$builddir"/"$busybox_name"/busybox
    
    rm -rf $outpath
    mkdir -p $outpath
    mkdir -p $builddir
    
    if [[ ! -f $builddir/$busybox_tarball ]]
    then
        wget -O $builddir/$busybox_tarball --tries=20 $busybox_url
    fi
    if [[ ! -d $builddir/$busybox_name ]]
    then
        tar --extract --bzip2 --touch --file="$builddir/$busybox_tarball" --directory="$builddir"
    fi
    cd $builddir/$busybox_name
    cp $busybox_src_config .config
    make -j "$(getconf _NPROCESSORS_ONLN)"
    export busybox="$busybox_image"
fi


mkdir -p $tmpdir/bin
mkdir -p $tmpdir/sbin
mkdir -p $tmpdir/etc
mkdir -p $tmpdir/dev
mkdir -p $tmpdir/proc
mkdir -p $tmpdir/sys
mkdir -p $tmpdir/lib
mkdir -p $tmpdir/var
mkdir -p $tmpdir/mnt
cp "$busybox" $tmpdir/bin/busybox
$tmpdir/bin/busybox --install $tmpdir/bin

mkdir -p $tmpdir/etc/init.d
cp $init $tmpdir/etc/init.d/rcS
chmod +x $tmpdir/etc/init.d/rcS

cp "$base"/inittab $tmpdir/etc/inittab
cp "$base"/passwd $tmpdir/etc/passwd

cp "$base"/autologin $tmpdir/bin
chmod +x $tmpdir/bin/autologin
cp "$base"/enter $tmpdir/bin
chmod +x $tmpdir/bin/enter

cd $tmpdir
find . | cpio --create --format='newc' > $tmpfile
gzip < $tmpfile > $initrd
sync

rm -rf $tmpdir
rm -rf $tmpfile
