#!/bin/bash

workpath=/usr/share/runX

containerid="$1"
state="$root"/"$containerid/state.json"
mountpoint=`cat $state | jq '.["config"]["rootfs"]'`
mountpoint=`sed -e 's/^"//' -e 's/"$//' <<<"$mountpoint"`
configfile="`dirname $mountpoint`"/"config.json"
appname=`cat $configfile | jq '.["Path"]'`
cmdline=`cat $configfile | jq  -c -r '.["Config"]["Cmd"] | join("\" \"")'`
cmdline="\"$cmdline\""

xl destroy $containerid &> /dev/null
