# Test jobs
qemu-alpine-arm64-gcc:
  stage: test
  image: registry.gitlab.com/lf-edge/runx/${CONTAINER}
  variables:
    CONTAINER: alpine:3.12-arm64v8
    CC: gcc
  script:
    - BASE=${BASE_SHA:-${CI_COMMIT_BEFORE_SHA}} TIP=${TIP_SHA:-${CI_COMMIT_SHA}} ./automation/gitlab-ci/build-each-commit.sh 2>&1 | tee ../build-each-commit-gcc.log
    - mv ../build-each-commit-gcc.log .
  dependencies: []
  artifacts:
    paths:
      - smoke.serial
      - '*.log'
    when: always
  tags:
    - arm64
  except:
    - master
    - smoke
    - /^coverity-tested\/.*/
    - /^stable-.*/


qemu-alpine-arm64-test:
  stage: test
  image: registry.gitlab.com/lf-edge/runx/${CONTAINER}
  variables:
    CONTAINER: alpine:3.12-arm64v8
    CC: gcc
  script:
    - ./automation/scripts/qemu-alpine-arm64.sh 2>&1 | tee qemu-smoke-arm64.log
  dependencies:
    - alpine-3.12-gcc-arm64
    - alpine-3.12-arm64-rootfs-export
    - kernel-5.10.30-arm64-export
    - qemu-system-aarch64-5.2.0-arm64-export
    - u-boot-2021.07-arm64-export
    - xen-4.14-arm64-export
  artifacts:
    paths:
      - smoke.serial
      - '*.log'
    when: always
  tags:
    - arm64
  except:
    - master
    - smoke
    - /^coverity-tested\/.*/
    - /^stable-.*/
